### ISSUE TITLE
Getting this error when trying to encrypt the gauth.csv file

### ISSUE THREAD

**Issue by ankit-timbadia** [pcarrier/gauth#31]
Ran this command as mentioned
openssl enc -aes-128-cbc -md sha256 -in gauth.csv -out gauth.csv

Encryption password:
           prev   curr   next
panic: runtime error: index out of range

goroutine 1 [running]:
main.main()
	/Users/ankit.timbadia/go/src/github.com/pcarrier/gauth/gauth.go:131 +0xcb7

**Comment by pcarrier** [comment]
Oops @ankit-timbadia I'm afraid that doesn't work in-place, and you replaced the file with an encrypted empty file.
