### ISSUE TITLE
Last line of SSL encrypted file decrypts incorrectly on win7/go.1.3

### ISSUE THREAD

**Issue by moshahmed** [pcarrier/gauth#32]
### Fixed in https://github.com/moshahmed/gauth/blob/gauth-vim-stdin-win7/gauth.go 

```
<     i := len(rest) - 1
<     for rest[i] < 16 {
---
>     i := len(rest)
>     for i>0 && rest[i-1] < 16 {

```

**Comment by moshgpr** [comment]
Fixed in https://github.com/moshahmed/gauth/blob/gauth-vim-stdin-win7/gauth.go 
<     i := len(rest) - 1
<     for rest[i] < 16 {
---
>     i := len(rest)
>     for i>0 && rest[i-1] < 16 {
