### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fabaff** [pcarrier/gauth#39]
Could you please add a license statement and a LICENSE file? It's a blocker to get `gauth` integrated into distributions, e. g., Fedora.

Thanks

BTW, if you don't mind, could you also create a release by tagging the source?

**Comment by pcarrier** [comment]
Sorry, of course! @creachadair I assume you OK with ISC, shared copyright?

```
$ git ls-tree -r -z --name-only HEAD -- **/*.go | xargs -0 -n1 git blame --line-porcelain HEAD |grep  '^author '|suc
    156 author M. J. Fromberger
```

**Comment by creachadair** [comment]
Works for me!

**Comment by pcarrier** [comment]
OK Solomon's contribution is the PKGBUILD, don't think there's any need to discuss ownership on largely metadata and a widespread pattern. Proceeding.

**Comment by pcarrier** [comment]
Forgot we already had a v1.0, tagged v1.1 unsigned (sorry left my gpg setup in another decade).
