### ISSUE TITLE
The ability to request only 1 code

### ISSUE THREAD

**Issue by ftk789** [pcarrier/gauth#48]
have the ability to just get one code, for an example:
```
C:\>gauth -snapchat
snapchat "code" "code" "code"
[ ======                      ]
C:\>
```

**Comment by fabiandiez** [comment]
Or even better, the ability to get only the current code, something like: 
`$ gauth --key=snapchat --type=current`

**Comment by ftk789** [comment]
> 

Assuming AWK is some kind of a package? I mean not all users use Linux, So what would that be in Windows?

**Comment by thepyzhov** [comment]
@ftk789 I'm not sure about Windows, but I guess [this post](https://stackoverflow.com/questions/21927944/how-to-run-an-awk-commands-in-windows) can help

**Comment by thepyzhov** [comment]
For example (if I have Google code): `$ gauth | awk '/Google/ {print $3}` works on Mac Terminal fine

Maybe for Windows `AWK` or `grep` another API

**Comment by ftk789** [comment]
> For example (if I have Google code): `$ gauth | awk '/Google/ {print $3}` works on Mac Terminal fine
> 
> Maybe for Windows `AWK` or `grep` another API

![image](https://github.com/pcarrier/gauth/assets/57598907/135b6ab2-09bf-4b5a-be7c-08e7519ef77b)
Needs an investigation, Thank you in any case.

**Comment by thepyzhov** [comment]
@ftk789 As I see, you've missed closing `'`. Should be `'/Discord/ {print $3}'`

**Comment by ftk789** [comment]
> @ftk789 As I see, you've missed closing `'`. Should be `'/Discord/ {print $3}'`

Oh sorry that was a mistake, Even with that still doesn't work, After some investigation, Seems like AWK for windows works only in PowerShell, Not a major issue, Thank you in any case, I can just create a bat file that runs a shell command in the background and just takes the input text as the codename. Thank you soo much.
