### ISSUE TITLE
Invalid block padding error after encrypting using opensll

### ISSUE THREAD

**Issue by ftk789** [pcarrier/gauth#50]
![image](https://user-images.githubusercontent.com/57598907/127681696-eaee5f9d-df9b-4534-9fb8-1a32b59309fd.png)

**Comment by ftk789** [comment]
I did the command again and i got this instead
![image](https://user-images.githubusercontent.com/57598907/127683897-eb41accd-9193-4f66-b73c-72701d297177.png)
and when i open the `gauth.csv` file i just see the encryption command and all of the secrets are deleted

**Comment by ftk789** [comment]
![image](https://user-images.githubusercontent.com/57598907/127684045-bd6442b2-c74d-404d-8d6d-ad6fbf488737.png)

**Comment by creachadair** [comment]
It sort of looks as if you used the same file for both `-in` and `-out` in the encryption command. I think that may not be safe to do: The tool may open and truncate the output file before it has read the input. 

The example on the repo kind of assumes the input and output are in two different directories, but I think from your example screenshots above, that's not the case here. We should probably update the example to make that explicit.

**Comment by ftk789** [comment]
![image](https://user-images.githubusercontent.com/57598907/127688077-e02bcc8b-7e0d-4273-b2b7-6ae30f321163.png)
 I tried this now, but when i run gauth it doesn't prompt me the password, it just executes it normally without encryption

**Comment by ftk789** [comment]
what should i do really, like what should i put the `-in` and the `-out` ?

**Comment by creachadair** [comment]
> what should i do really, like what should i put the `-in` and the `-out` ?

What I think will make it safe is to copy the original (unencrypted) input file to a different location from the output, before running the command. Something like, maybe:

```sh
cp ~/.config/gauth.csv ~/input.csv
openssl enc -aes-128-cbc -md sha256 -in ~/input.csv -out ~/.config/gauth.csv
```

or something similar to that. I also updated the example in the README to make that more explicit.

**Comment by ftk789** [comment]
And... it works smoothly, then it was on my end, thank you soo much, great project <3
