### ISSUE TITLE
The ability to add new secrets using prefixes

### ISSUE THREAD

**Issue by ftk789** [pcarrier/gauth#51]
The ability to add new secrets using prefixes, for an example
```
C:\>gauth -add Twitter:"secret"
gauth:the new secret has been added
C:\>gauth
Twitter "code" "code" "code"

```

**Comment by pcarrier** [comment]
Personally comfortable using an editor, but I'd absolutely take a pull request to that effect.

**Comment by creachadair** [comment]
> Personally comfortable using an editor, but I'd absolutely take a pull request to that effect.

I think the tricky part about implementing this would be dealing with an encrypted config file. A minimum viable solution could just report an error if the file is encrypted, but it'd still have to detect that.

**Comment by ftk789** [comment]
i mean it's not really important, and i would use the editor too, but just for the people that love the "plug and play" word, instead of them going to the file and edit it, they just add it, cool feature to have, and yea the encryption would ruin it, unless there is a way around that
