### ISSUE TITLE
Provide prebuilt binaries for released versions

### ISSUE THREAD

**Issue by and-semakin** [pcarrier/gauth#56]
Hi! Thanks for your awesome tool!

It would be nice to be able to just download a prebuilt binary from the releases page on GitHub. Of course, I can build it myself, but I need to install the Go compiler to do this and I'm not a Go developer, so, it's some kind of inconvenient.

**Comment by pcarrier** [comment]
Agreed :) If anybody is up for the task of automating it, I'd be more than happy to merge.

**Comment by hu13** [comment]
@pcarrier I should be able to do using goreleaser unless somebody else beats me to it. Will let you know.

**Comment by pcarrier** [comment]
@hu13 sounds great, thanks!

**Comment by pcarrier** [comment]
v1.2.0 was released with binaries today, thanks to @hu13's great work :)

**Comment by and-semakin** [comment]
Awesome! Thank you so much @hu13!
