### ISSUE TITLE
Is this QR code tool of any interest?

### ISSUE THREAD

**Issue by jbert** [pcarrier/gauth#64]
Hi,

Thanks for gauth - it's a great tool.

I recently found myself needing to export an OTP secret from google authenticator on my phone to my gauth.csv file.

So this tool is a simple step in doing that (wrapping `zbarimg` to perform the QR extraction).

https://github.com/jbert/gauthQR

regards,

jb

**Comment by pcarrier** [comment]
Thank you! Would you like to open a pull request to update README.md and point to it?
