### ISSUE TITLE
Decrypting using openssl so that I can add new entries

### ISSUE THREAD

**Issue by djmills64** [pcarrier/gauth#67]
I have an encrypted gauth.csv and can get the codes using a passphrase. I want to decrypt, add some extra secret keys/accounts and re-encrypt. But I can't seem to work out the command line to do the decryption. Please advise.

**Comment by djmills64** [comment]
I tried
`openssl enc -aes-256-cbc -md sha256 -d -in x.enc -out x.txt`
but get 
`bad decrypt
140529509025088:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:610:`

**Comment by creachadair** [comment]
That error message appears to result from an incorrect passphrase being provided during decryption.

**Comment by djmills64** [comment]
I figured it out. I was using -aem-256-cbc but it needed to be 128.

Thanks for your help.

Cheers,

David

Mob: +61-4-11513404

**Comment by djmills64** [comment]
`openssl enc -aes-128-cbc -md sha256 -d -in x.enc -out x.txt`
worked.

**Comment by pcarrier** [comment]
Thanks for letting us know!
