### ISSUE TITLE
.config location used by other programs too.

### ISSUE THREAD

**Issue by madtechsupport** [pcarrier/gauth#7]
Hi,

I noticed that wireshark also sets up its default configuration in .config.

```
➜  ~  cd .config
➜  .config  ls
gauth.csv wireshark
```

Regards,

Warren.

**Comment by bAndie91** [comment]
it's a standard to save files in `~/.config`,  in separate file/folder for each apps.
they are not conflicting till some other app wont write to `~/.config/gauth.csv` itself.

**Comment by pcarrier** [comment]
Yes `.config` is indeed a reasonable location for many programs to store their config. Ideally we should use the `XDG_CONFIG_HOME` environment variable with a fallback to `~/.config` as per https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
