### ISSUE TITLE
Stopped working with Google?

### ISSUE THREAD

**Issue by xhyp0** [pcarrier/gauth#9]
I've been using your tool at https://github.com/pcarrier/gauth and it's been great so far. However, I noticed that it seems to have stopped working for my Google account. I've tried generating new codes multiple times, but the output from your tool is still different than the one from the Google Authenticator app. The other 2FA codes seem to work properly.

Is there anything that might have changed with how Google handles 2FA?

**Comment by llwp** [comment]
This appears resolved.

**Comment by pcarrier** [comment]
You might have had a clock synchronization issue? Anyway glad to hear everything works, sorry for the terrible response time.
